---
name: Bug report
about: Report a bug or issue in Vanilla Calendar Pro
title: "[BUG]"
labels: bug
assignees: ''
---

**⚠️ Important: Bug reports are accepted only for version 3.0.0 or above**
Before submitting a bug report, ensure that you are using at least version **3.0.0** of Vanilla Calendar Pro. Issues reported for earlier versions will not be addressed.

---

**Describe the bug**
Provide a clear and concise description of the issue related to Vanilla Calendar Pro.

**Steps to reproduce**
Please list the exact steps to reproduce the issue:
1. Include the version of Vanilla Calendar Pro you are using.
2. Describe the setup process or initialization of the calendar.
3. Detail the actions taken before encountering the bug.

**Expected behavior**
What was the expected outcome or behavior of Vanilla Calendar Pro?

**CodeSandbox example (REQUIRED)**
To help us debug efficiently, you **must** create a reproducible example of the issue in a sandbox environment.
Use [CodeSandbox](https://codesandbox.io/) or a similar tool to replicate the problem, and provide the link here:
> Example link: https://codesandbox.io/p/sandbox/eloquent-dubinsky-cfthqk

**Screenshots (optional)**
If applicable, attach screenshots or GIFs to illustrate the problem.

**Additional context**
Include any additional details, such as custom configurations, integrations, or any logs related to the issue.
