---
name: Feature request
about: Suggest a new feature or improvement for Vanilla Calendar Pro
title: "[FEATURE]"
labels: enhancement
assignees: ''
---

**⚠️ Important: Check before submitting**
Before proposing a new feature, ensure:
1. The feature does not already exist in Vanilla Calendar Pro.
2. It cannot be implemented using the current settings or customization options.

---

**Feature description**
Describe the feature or enhancement you would like to see in Vanilla Calendar Pro. Be specific and concise.

**Use case**
Explain why this feature is important.
- What problem does it solve?
- How would it improve the user experience?

**Proposed solution**
If you have an idea of how this feature could be implemented, describe it here. This can include API suggestions, functionality details, or UI/UX considerations.

**Similar functionality in other calendars (optional)**
If you know of another calendar that has this feature, please share its name and describe how it works.

**Alternatives considered**
If you have explored other solutions, mention them and explain why they are insufficient for your needs.

**Additional context**
Add any additional information, related discussions, or references that might help us understand and prioritize your request.
