name: Testing pull request

on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm package
        run: npm ci
      - name: Testing
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
